swagger: "2.0"
info:
  title: Gpt API
  description: AI assistant for analysing PDFs.
  version: "1.0.0"
host: localhost:5002
basePath: "/"
schemes:
  - http
paths:
  /set-background:
    post:
      description: ""
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              background:
                example: any
      responses:
        200:
          description: OK
        400:
          description: Bad Request
  /get-response:
    get:
      description: ""
      parameters:
        - name: text
          in: query
          type: string
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        500:
          description: Internal Server Error
